logging:
  level:
    org.springframework.web: WARN
    com.epam.shop: DEBUG
server:
  port: 8080
spring:
  sql:
    init:
      mode: always
  liquibase:
#    url:  jdbc:oracle:thin:@//172.17.0.2:1521/ORCLPDB1
#    user: prod_user
#    password: My_admin878
    enabled: true
#    driver-class-name: oracle.jdbc.driver.OracleDriver
    change-log: classpath:liquibase/db.changelog-master.xml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
#    database: oracle
#    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
  test:
    database:
      replace: none
#  datasource:
#    url: jdbc:oracle:thin:@//172.17.0.2:1521/ORCLPDB1
#    password: My_admin878
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    username: prod_user
jwt:
  secretKey: mypSecretKey
  header: Authorization
  expiration: 86400